genre=input("What is your fav genre:")
print(f"my fav genre is {genre}")
language=input("What is your fav language movies:")
print(f"I love watching {language} movies")
anime=list(map(str,input("what are your fav anime:").split()))
print(anime)