name=input("What is your name:")
print(f"My name is {name}")
age=int(input("What is your age:"))
print(f"I am {age} years old")
country=input("Which country are you form:")
print(f"I am from {country}")